<a href="https://colab.research.google.com/github/swasfish-code/python/blob/main/IITH_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks = np.array([75, 82, 91, 68, 88])

print(marks)

[75 82 91 68 88]


In [ ]:
type(marks)

numpy.ndarray

In [ ]:
marks.ndim

1

In [ ]:
marks.shape

(5,)

In [ ]:
print(marks[2])

91


In [ ]:
a = [
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [70, 68, 75]
]

In [ ]:
type(a)

list

In [ ]:
marks = np.array(a)

print(marks)

[[80 75 90]
 [65 70 72]
 [88 92 85]
 [70 68 75]]


In [ ]:
marks.ndim

2

In [ ]:
marks.shape

(4, 3)

In [ ]:
| Student   | Math | Python | SQL |
| --------- | ---: | -----: | --: |
| Student 1 |   80 |     75 |  90 |
| Student 2 |   65 |     70 |  72 |
| Student 3 |   88 |     92 |  85 |
| Student 4 |   70 |     68 |  75 |


In [ ]:
print(marks)

[[80 75 90]
 [65 70 72]
 [88 92 85]
 [70 68 75]]


In [ ]:
marks[0][0]

np.int64(80)

In [ ]:
marks[2][1]

np.int64(92)

In [ ]:
marks[2,1]

np.int64(92)

In [ ]:
marks[2]

array([88, 92, 85])

In [ ]:
marks = np.array([75, 82, 91, 68, 88])

print(marks)

[75 82 91 68 88]


In [ ]:
n = len(marks)
n

5

In [ ]:
marks[n-1]

np.int64(88)

In [ ]:
marks[4]

np.int64(88)

In [ ]:
marks[-1]

np.int64(88)

In [ ]:
marks[-2]

np.int64(68)

In [ ]:
m1 = np.array(a)
m1

array([[80, 75, 90],
       [65, 70, 72],
       [88, 92, 85],
       [70, 68, 75]])

In [ ]:
m1[-1]

array([70, 68, 75])

In [ ]:
m1[-1,-1]

np.int64(75)

In [ ]:
marks

array([75, 82, 91, 68, 88])

In [ ]:
marks[0:3]

array([75, 82, 91])

In [ ]:
marks[:3]

array([75, 82, 91])

In [ ]:
marks[1:4]

array([82, 91, 68])

In [ ]:
marks[2:]

array([91, 68, 88])

In [ ]:
marks[-3:]

array([91, 68, 88])

In [ ]:
marks

array([75, 82, 91, 68, 88])

In [ ]:
m1

array([[80, 75, 90],
       [65, 70, 72],
       [88, 92, 85],
       [70, 68, 75]])

In [ ]:
marks

array([75, 82, 91, 68, 88])

In [ ]:
marks[::]

array([75, 82, 91, 68, 88])

In [ ]:
m1

array([[80, 75, 90],
       [65, 70, 72],
       [88, 92, 85],
       [70, 68, 75]])

In [ ]:
m1[:,0]

array([80, 65, 88, 70])

In [ ]:
m1[:, 2]

array([90, 72, 85, 75])

In [ ]:
m1[:,-1]

array([90, 72, 85, 75])

In [ ]:
students = np.array([
    [101, 85, 90, 88],
    [102, 78, 82, 80],
    [103, 92, 95, 94],
    [104, 70, 75, 72],
    [105, 88, 84, 90]
])

In [ ]:
# Column 0 → Student ID
# Column 1 → Python
# Column 2 → SQL
# Column 3 → NumPy

In [ ]:
id = students[:,0]
id

array([101, 102, 103, 104, 105])

In [ ]:
python = students[:,1]
python

array([85, 78, 92, 70, 88])

In [ ]:
sql = students[:,2]
sql

array([90, 82, 95, 75, 84])

In [ ]:
nump = students[:,3]
nump

array([88, 80, 94, 72, 90])

In [ ]:
python[-2:]

array([70, 88])

In [ ]:
students

array([[101,  85,  90,  88],
       [102,  78,  82,  80],
       [103,  92,  95,  94],
       [104,  70,  75,  72],
       [105,  88,  84,  90]])

In [ ]:
students[:2, :]

array([[101,  85,  90,  88],
       [102,  78,  82,  80]])

In [ ]:
students[1:4:2]

array([[102,  78,  82,  80],
       [104,  70,  75,  72]])

In [ ]:
students[[1,3,4]]

array([[102,  78,  82,  80],
       [104,  70,  75,  72],
       [105,  88,  84,  90]])

In [ ]:
students

array([[101,  85,  90,  88],
       [102,  78,  82,  80],
       [103,  92,  95,  94],
       [104,  70,  75,  72],
       [105,  88,  84,  90]])

In [ ]:
students[:,[1,3]]

array([[85, 88],
       [78, 80],
       [92, 94],
       [70, 72],
       [88, 90]])

In [ ]:
#sum of all the python marks:

np.sum(python)

np.int64(413)

In [ ]:
np.mean(python)

np.float64(82.6)

In [ ]:
np.median(python)

np.float64(85.0)

In [ ]:
python

array([85, 78, 92, 70, 88])

In [ ]:
np.min(python)

np.int64(70)

In [ ]:
np.max(python)

np.int64(92)

In [ ]:
You are given the marks of 5 students in Python, SQL, and NumPy.

import numpy as np

marks = np.array([
    [85, 90, 88],
    [72, 75, 70],
    [92, 95, 94],
    [65, 68, 72],
    [80, 85, 82]
])

In [ ]:
Extract the marks of the third student.

Extract all Python marks.

Extract SQL and NumPy marks of all students.

Calculate the average mark of each student

In [ ]:
marks = np.array([
    [85, 90, 88],
    [72, 75, 70],
    [92, 95, 94],
    [65, 68, 72],
    [80, 85, 82]
])

In [ ]:
# Extract the marks of the third student.
marks[2]

array([92, 95, 94])

In [ ]:
# Extract all Python marks.
marks[:,0]

array([85, 72, 92, 65, 80])

In [ ]:
# Extract SQL and NumPy marks of all students.

marks[:,1:3]

array([[90, 88],
       [75, 70],
       [95, 94],
       [68, 72],
       [85, 82]])

In [ ]:
# Calculate the average mark of each student --HW
marks

array([[85, 90, 88],
       [72, 75, 70],
       [92, 95, 94],
       [65, 68, 72],
       [80, 85, 82]])

In [ ]:
A company records its sales for 6 months across 3 products.

import numpy as np

sales = np.array([
    [12000, 15000, 18000],
    [14000, 16000, 17500],
    [11000, 14500, 19000],
    [15500, 17000, 20000],
    [13000, 16500, 18500],
    [16000, 18000, 21000]
])

Each row represents a month and the columns represent:

Column 0 → Product A
Column 1 → Product B
Column 2 → Product C

In [ ]:
Extract sales for Product A.

Extract sales for the first 3 months.

Extract Product B and Product C sales for the last 3 months.

In [ ]:
sales = np.array([
    [12000, 15000, 18000],
    [14000, 16000, 17500],
    [11000, 14500, 19000],
    [15500, 17000, 20000],
    [13000, 16500, 18500],
    [16000, 18000, 21000]
])

In [ ]:
sales[:,0]

array([12000, 14000, 11000, 15500, 13000, 16000])

In [ ]:
sales[:3]

array([[12000, 15000, 18000],
       [14000, 16000, 17500],
       [11000, 14500, 19000]])

In [ ]:
sales[-3:,-2:]

array([[17000, 20000],
       [16500, 18500],
       [18000, 21000]])